services:
  - type: web
    name: passive-income-node
    env: docker
    region: ohio
    plan: free
    branch: main
    autoDeploy: true
    envVars:
      - key: EARNFM_TOKEN
        sync: false
      - key: TM_TOKEN
        sync: false
      - key: RP_EMAIL
        sync: false
      - key: RP_API_KEY
        sync: false
